FROM golang:1.20 AS builder
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY main.go .
RUN CGO_ENABLED=0 go build -o app

FROM gcr.io/distroless/static-debian11
WORKDIR /app
COPY --from=builder /app/app /app/app
ENTRYPOINT ["/app/app"]
